# Generated by Django 6.0.3 on 2026-03-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
