# Generated by Django 6.0.3 on 2026-03-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_profile_image_seller_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='0943803129', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(default='0943803129', max_length=11),
            preserve_default=False,
        ),
    ]
