# Generated by Django 6.0.4 on 2026-04-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customer_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
    ]
