# Generated by Django 6.0.2 on 2026-03-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_first_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
