# Generated by Django 6.0.2 on 2026-03-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='order_items',
            new_name='order',
        ),
    ]
