# Generated by Django 6.0.3 on 2026-03-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
