# Generated by Django 6.0.2 on 2026-02-20 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_chat_session_id_chat_user_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='chat',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
