# Generated by Django 6.0.2 on 2026-02-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chat_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
