# Generated by Django 6.0.2 on 2026-02-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_chatmessage_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='MetaData',
            field=models.JSONField(null=True),
        ),
    ]
